### ISSUE TITLE
Example code mistake

### ISSUE THREAD

**Issue by Raikao** [yuehhua/GeometricFlux.jl#1]
Hi!

I was trying to replicate your example code for the GCN and I think there's one small mistake on the accuracy function, when calculating the onecold you are supposed to transpose the matrix in order to get the 7 variable transformation.

`
accuracy(x, y) = mean(onecold(model(x)') .== onecold(y'))
`

BR.

**Comment by yuehhua** [comment]
Thank you for trying this project.
I found this issue and it is related to the dimension of input/output.
I changed the calculation of layers to be compatible with layers in Flux.
You may want to try it in latest develop branch.

**Comment by Raikao** [comment]
Hi again!

Now it works without problems! Great work btw! 

BR.
