### ISSUE TITLE
LightGraphs dependency warning

### ISSUE THREAD

**Issue by rkurchin** [yuehhua/GeometricFlux.jl#24]
I’m using GeometricFlux and building my graphs using SimpleWeightedGraph. However, it seems to get some of the functions I need I also have to import LightGraphs itself (for example, the `add_edge!` function). Then, when I import GeometricFlux I get this warning:

```
┌ Warning: Package GeometricFlux does not have LightGraphs in its dependencies:
│ - If you have GeometricFlux checked out for development and have
│   added LightGraphs as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with GeometricFlux
└ Loading LightGraphs into GeometricFlux from project dependency, future warnings for GeometricFlux are suppressed.
```

I brought this up on the #graphs channel in the Slack and Dhairya suggested I report it here.

**Comment by yuehhua** [comment]
Thank s for trying this package!
I will deal with it ASAP. Wait for new bug fix.

**Comment by yuehhua** [comment]
The warning is just fine. It doesn't affect the use of LightGraphs and GeometricFlux anyway.
I will keep this open until the warning is solved.

**Comment by yuehhua** [comment]
Solved.
