### ISSUE TITLE
Support for graph nets

### ISSUE THREAD

**Issue by sdewaele** [yuehhua/GeometricFlux.jl#36]
It is great to see GeometricFlux growing fast!

Graph nets are a [generic framework](https://arxiv.org/abs/1806.01261) proposed for graph processing - see also this [tutorial](https://grlearning.github.io/slides/battaglia.pdf) and [Python implementation](https://github.com/deepmind/graph_nets). It would be great if GeometricFlux would support this framework.

The graph network as a special case supports [GCNConv but with different graphs](https://discourse.julialang.org/t/geometricflux-gcnconv-but-with-different-graphs/36518) - also discussed in https://github.com/yuehhua/GeometricFlux.jl/issues/6. For example, a graph net can also operate on edge properties.

Perhaps this type of framework is too generic for what you have in mind for GeometricFlux. At least, I hope that the referred papers/tutorials help to further motivate support for different shape graphs, which I think is an important capability of a graph processing package.

**Comment by CarloLucibello** [comment]
A slightly less general, but already quite flexible framework, is the one of Message Passing Neural Networks, described in eqs. 1 and 2 of this influential paper:
https://arxiv.org/pdf/1704.01212.pdf

**Comment by yuehhua** [comment]
So far, GeometricFlux has already support both two frameworks mentioned above.
For graph net, you may want to check [here](https://github.com/yuehhua/GeometricFlux.jl/blob/master/src/layers/meta.jl). I have already designed several kinds of update and aggregate functions for vertex, edges and globals.
For message-passing framework, I crafted it as a special case of GN and you may want to check it [here](https://github.com/yuehhua/GeometricFlux.jl/blob/master/src/layers/msgpass.jl). It supports two update functions and one aggregate function.
The lost thing here is lacking tests and documentations, so I need to come out with both soon.

**Comment by sdewaele** [comment]
Thanks for pointing this out. If it works in conjunction with the variable graphs, then this will reproduce the flexibility of graph_net. That's great!

**Comment by yuehhua** [comment]
As for the compatibility to variable graph, I have to test and check again.
Before that...........I have to pass my midterm exam this week..............

**Comment by sdewaele** [comment]
Of course. Good luck with the exam!

**Comment by XVilka** [comment]
By the way, what was the resolution about compatibility with variable graphs?

**Comment by yuehhua** [comment]
@XVilka Check #42 please.

**Comment by sdewaele** [comment]
Thanks for the pointer to the [meta layer](https://github.com/yuehhua/GeometricFlux.jl/blob/d8b343776a3e6d35387ddba3a21fd58bdd0fdd29/src/layers/meta.jl).  The update functions `update_edge` etc. are what I am looking for. Is this planned to become a full-fledged trainable layer for Flux, i.e., the object will be callable, and we can get its `params`? Perhaps I have overlooked it; I have not gone through all of the code in detail yet.

**Comment by yuehhua** [comment]
I rewrite `Meta` into `GraphNet` for soundly implementation, and get `MessagePassing` support as a whole.
Check #63

**Comment by sdewaele** [comment]
That is a significant enhancement, great!

**Comment by yuehhua** [comment]
I think `GraphNet` is supported now and I will add graph net example and some test cases further.
