### ISSUE TITLE
Sound support of variable graphs

### ISSUE THREAD

**Issue by yuehhua** [yuehhua/GeometricFlux.jl#42]
There are more and more applications in GNN. In training, people demand model to be trained on distinct graphs. Variable graphs are needed to customize their training process.
So far, I implement the `FeaturedGraph` to equip graph structure on features, so one can input feature with a graph. However, it is experimentally implemented to support `GCNConv`. To support all layers, there are more work to do.

**Comment by ilancoulon** [comment]
First, thank you for your work on GeometricFlux.jl 😃 


Are you currently working on that issue?
If not, could I try implemeting some other layers?
Finally, is the `FeaturedGraph` struct going to last? Should we use MetaGraphs.jl instead or is it better to keep that structure? (as discussed in https://github.com/yuehhua/GeometricFlux.jl/issues/6)

**Comment by yuehhua** [comment]
I am welcome and happy to receive contributions from others.
I will maintain `FeaturedGraph` in the mainstream. As for the MetaGraph support, I will keep the conversion to `FeaturedGraph` available.
If one wants to design new layer, please take `FeaturedGraph` as first choice.

**Comment by ilancoulon** [comment]
Actually, it seems #36 does not fully add the supports for FeaturedGraph/GCNConv. I'd say it is the same for #44.
Indeed, trying to compute the gradient with a featured graph seems to throw an error. I'll investigate more and start a draft PR about this.

**Comment by yuehhua** [comment]
`FeaturedGraph` is supported by graph net and message passing scheme in #63

**Comment by tdfalc** [comment]
Hi, thank you for the awesome package! Im curious how the GCNConv layer incorporates edge features from the FeaturedGraph type? And what structure the the edge features should take, i.e. can the features for each edge be greater than 1 dim?

**Comment by yuehhua** [comment]
@tdfalc Thank you for your question. Would you please open another issue for this? I will give you a reply in that issue.
